### ISSUE TITLE
抱歉，没找到其他联系方式。咨询一个python package的问题

### ISSUE THREAD

**Issue by spwei** [iamfat/gini#48]
你好，非常抱歉，在这里提交一个和本项目无关的问题。
请问https://pypi.python.org/pypi/aliyun-python-sdk-alidns/2.0.0上的Package Index Owner: iamfat是你的账号吗？
目前我们想更新aliyun-python-sdk-alidns的版本，正在尝试联系iamfat的账号持有人。

**Comment by iamfat** [comment]
啊 对的... 那个是我提交的..

**Comment by iamfat** [comment]
这个我能自助transfer ownership吗? 好像pypi那边我没找到..

**Comment by spwei** [comment]
通过：https://docs.python.org/2/distutils/packageindex.html描述：
 Changes can be submitted through the register command or through the web interface. Owners can designate other users as Owners or Maintainers. Maintainers can edit the package information, but not designate new Owners or Maintainers.

麻烦先从web界面是否可以移交给alexjxd这个账户

**Comment by spwei** [comment]
你也可以直接删除这个包，然后我们再重新上传

**Comment by iamfat** [comment]
我删完了，你试试看?

黄嘉
基理科技
http://www.geneegroup.com
Research Gets Easier!

**Comment by spwei** [comment]
非常感谢您的支持，我们已经重新发布新版SDK。
