### ISSUE TITLE
如果在gini index publish的时候输入凭证 就会500

### ISSUE THREAD

**Issue by HuangStomach** [iamfat/gini#51]
root@24fc847d212f:/data/gini-modules/bzmc-gateway# gini index publish 0.1.0
NOTICE: You are currently executing commands without cache!

Publishing bzmc-gateway/0.1.0...

User: jipeng.huang
Password:

Error: 500
root@24fc847d212f:/data/gini-modules/bzmc-gateway# gini index login
NOTICE: You are currently executing commands without cache!

User: jipeng.huang
Password:
You've successfully logged in as jipeng.huang.

这是终端输出 如果我在使用gini index publish命令的时候就会抛出500错误
正常分步登陆没有问题

**Comment by HuangStomach** [comment]
root@24fc847d212f:/data/gini-modules/girl# gini index publish 0.2.0
Publishing girl/0.2.0...

User: jipeng.huang
Password:

girl/0.2.0 was published successfully.

没再复现

**Comment by iamfat** [comment]
😆 已修复

Inviato da iPhone
