### ISSUE TITLE
router路由匹配问题

### ISSUE THREAD

**Issue by HuangStomach** [iamfat/gini#53]
发现如果定义router为 
``` php
$router->post('a/b/{id}', 'A@b');
```
参数列表为 
``` php
function b ($id) { }
```

将参数写入url进行post提交的时候一切正常
但使用 `form-data` 参数为 `{ 'id': 1 }`  提交至`a/b`时则无法匹配到相应路由
如果url随便写占用`{id}`的位置时 如 `a/b/sth` 则可以正常匹配

另外如果我为了捕获跟路由写出
``` php
$router->('/', 'class@action');
```
则除非我重新定义全部路由 否则没有定义的路由均会被该条路由规则拦截
是否设计如此？

**Comment by iamfat** [comment]
对的，现在的简化设计就会造成这样... 这也是为什么我前面提到是不是一个是根据匹配的模式长度做一个排序，命中路径环节细节更多的在前面命中，另外是做一个`throw new DispatchToNextException`之类的方法可以把不合适的处理直接扔回dispatch机制中传递到下一命中中，不过我们目前的机制后面一个方法会麻烦很多。

**Comment by HuangStomach** [comment]
那么其实参数列表的用法是不是应该暂时搁置……
有时间修一修再用吧

**Comment by iamfat** [comment]
为啥呢?

黄嘉 Jia Huang

天津市基理科技股份有限公司
地址：天津市西青区海泰南道18号左岸花园16幢2栋
电话：18622960693
Email: jia.huang@geneegroup.com 
官网：www.geneegroup.com 
全国客服热线: 400-617-5664

**Comment by HuangStomach** [comment]
可以关闭
