### ISSUE TITLE
gini web update 命令中 less转换出现问题

### ISSUE THREAD

**Issue by HuangStomach** [iamfat/gini#74]
具体原因详见 [less issues#974](https://github.com/less/less.js/issues/974)

我们在引入某些第三方ui框架如**bootstrap**或自己进行某些计算式`height: calc(2.25rem + 2px);`的时候

less会将`height: calc(2.25rem + 2px);`直接转换为`height: 4.25rem`

根据issue所示，可以通过将`class/Gini/Controller/CLI/Web.php`中`55`行左右:

``` php
$command = sprintf(
    'lessc %s %s %s',
    escapeshellarg($src_path),
    escapeshellarg($dst_path),
    '--clean-css="--s1 --advanced --compatibility=ie8"'
        );
exec($command);
```

修改为

``` php
$command = sprintf(
    'lessc %s %s %s',
    escapeshellarg($src_path),
    escapeshellarg($dst_path),
    '--clean-css="--s1 --advanced --compatibility=ie8" --strict-math=on'
        );
exec($command);
```

就可以正常的解析，是否考虑增加`web update`的参数还是直接加入框架中？

**Comment by iamfat** [comment]
直接先PR加这个参数吧

发自我的 iPhone

**Comment by HuangStomach** [comment]
#77
